# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utterance',
            name='Utterance',
        ),
        migrations.AddField(
            model_name='utterance',
            name='utterance',
            field=models.CharField(default='', max_length=400),
        ),
    ]
