# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20161227_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(default='', max_length=400)),
                ('entity', models.CharField(default='', max_length=100)),
                ('entity_type', models.CharField(default='', max_length=100)),
                ('bot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Bot')),
            ],
        ),
    ]
